title: Pankaj
description: Dumping space for my learnings, thoughts and experiences. 
author: Pankaj Yadav
avatar: /logo.png
# email: 

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: G-BXS3XY0WT3

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Guruji_Panks
  card: summary
logo: logo.png
social:
  name: Pankaj Yadav
  links:
    - https://twitter.com/Guruji_Panks
    - https://github.com/y-pankaj
google_site_verification: PzRp9o3IMUcwRZYOchKpJK8tG8AwWCClyBBOofOz5ak
lang: en
